version: '3'

tasks:
  docker-local:
    desc: Start Docker containers locally (monitor + infrastructure)
    cmds:
      - docker compose -f ./deploy/monitor/docker-compose.yml -f ./deploy/infrastructure/docker-compose.yml up -d

  docker-down:
    desc: Stop Docker containers
    cmds:
      - docker compose -f ./deploy/monitor/docker-compose.yml -f ./deploy/infrastructure/docker-compose.yml down

  docker-logs:
    desc: View logs from Docker containers
    cmds:
      - docker compose -f ./deploy/monitor/docker-compose.yml -f ./deploy/infrastructure/docker-compose.yml logs -f
  
  fe:
    desc: Start frontend development server
    cmds:
      - npm run dev:fe
  
  be:
    desc: Start backend development server
    cmds:
      - npm run dev:be
  
  fullstack:
    desc: Start fullstack development server
    cmds: 
      - sh -lc 'npm run dev:be & npm run dev:fe & wait'
  
  lint:
    desc: Lint the code
    cmds:
      - npm run lint:all
  
  prisma-generate:
    desc: Generate Prisma client
    cmds:
      - cd be && npx prisma generate
  
  prisma-push:
    desc: Push Prisma schema to database
    cmds:
      - cd be && npx prisma db push
  
  prisma-all:
    desc: Generate Prisma client and push Prisma schema to database
    cmds:
      - task: prisma-generate
      - task: prisma-push
  
  docker-restart:
    desc: Restart Docker containers
    cmds:
      - task: docker-down
      - task: docker-local