// This file was generated by the protobuf compiler. Do not edit.
//==================================================
export interface CreateStorageRequest {
  storeId: string;
  name: string;
  isPrimary?: boolean;
  active?: boolean;
  address?: string;
  color?: string;
  icon?: string;
}

export interface CreateStorageResponse {
  storageId?: string;
}

export interface GetStorageByIdRequest {
  storageId: string;
}

export interface GetStorageByStoreIdRequest {
  storeId: string;
}

export interface GetStorageByStoreIdResponse {
  storages: StorageResponse[];
}

export interface StorageResponse {
  id: string;
  storeId: string;
  name: string;
  isDelete: boolean;
  isPrimary: boolean;
  createdAt: google.protobuf.Timestamp;
  updatedAt: google.protobuf.Timestamp;
  address?: string;
  color?: string;
  icon?: string;
  active: boolean;
}

export interface StorageResponseOverview {
  id: string;
  storeId: string;
  name: string;
  isDelete: boolean;
  isPrimary: boolean;
  createdAt: google.protobuf.Timestamp;
  updatedAt: google.protobuf.Timestamp;
  address?: string;
  color?: string;
  icon?: string;
  active: boolean;
  itemCount: number;
  totalValue: number;
  lowStockValue: number;
}

export interface GetStorageByStoreIdOverviewResponse {
  storages: StorageResponseOverview[];
}

export interface UpdateStorageRequest {
  storageId: string;
  name: string;
  active?: boolean;
  address?: string;
  color?: string;
  icon?: string;
}

export interface UpdateStorageResponse {
  storageId?: string;
}

export interface RemoveStorageRequest {
  storageId: string;
}

export interface RemoveStorageResponse {
  storageId?: string;
}
//==================================================