// This file was generated by the protobuf compiler. Do not edit.
//==================================================
export interface CreateStoreRequest {
  name: string;
}

export interface CreateStoreResponse {
  storeId?: string;
}
//==================================================