// This file was generated by the protobuf compiler. Do not edit.
//==================================================
export interface CreateStoreRequest {
  name: string;
}

export interface CreateStoreResponse {
  storeId?: string;
}

export interface GetUserInfoRequest {
  userId: string;
}

export interface StoreInfo {
  id: string;
  name: string;
}

export interface GetUserInfoResponse {
  email?: string;
  name?: string;
  storeInfos: StoreInfo[];
}
//==================================================