// This file was generated by the protobuf compiler. Do not edit.
//==================================================

export interface CreateCategoryRequest {
  name: string;
  layer: string;
  description?: string;
}

export interface CreateCategoryResponse {
  categoryId?: string;
}

export interface GetCategoryResponse {
  categoryId?: string;
  name?: string;
  parentId?: string;
  description?: string;
  colorSettings?: string;
  layer?: string;
  imageUrl?: string;
  subCategoriesCount?: number;
}

export interface GetCategoryRequest {
  categoryId: string;
}

export interface RemoveCategoryRequest {
  categoryIds: string[];
}

export interface RemoveCategoryResponse {
  removedCount: number;
}

//==================================================