// This file was generated by the protobuf compiler. Do not edit.
//==================================================
export interface CreateProductRequest {
  storeId: string;
  categoryId?: string;
  name: string;
  description?: string;
  imageUrl?: string;
  status?: string;
  baseUnitCode?: string;
  baseUnitLabel?: string;
  sellPrice: number;
  exportPrice?: number;
  trackingMode?: string;
  containerLabel?: string;
  containerSize?: number;
  packs: CreateProductPackRequest[];
  barcodes: CreateProductBarcodeRequest[];
}

export interface CreateProductPackRequest {
  name: string;
  multiplier: number;
  barcodes: CreateProductBarcodeRequest[];
}

export interface CreateProductBarcodeRequest {
  value: string;
  isActive?: boolean;
}

export interface CreateProductResponse {
  productId?: string;
}

export interface GetProductByIdRequest {
  productId: string;
}

export interface ProductBarcodeResponse {
  id: string;
  storeId: string;
  value: string;
  productId: string;
  packId?: string;
  isActive: boolean;
}

export interface ProductPackResponse {
  id: string;
  storeId: string;
  productId: string;
  name: string;
  multiplier: number;
  sellPrice?: number;
  barcodes: ProductBarcodeResponse[];
}

export interface ProductResponse {
  id: string;
  storeId: string;
  categoryId?: string;
  description?: string;
  imageUrl?: string;
  name: string;
  status: string;
  isDelete: boolean;
  baseUnitCode: string;
  baseUnitLabel?: string;
  sellPrice: number;
  exportPrice?: number;
  trackingMode: string;
  containerLabel?: string;
  containerSize?: number;
  packs: ProductPackResponse[];
  barcodes: ProductBarcodeResponse[];
}
//==================================================