name: Build FE Image

on:
  pull_request:
    branches:
      - main
      - test
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    name: Build and push FE image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/jade-fe
      IMAGE_TAG: ${{ inputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DockerfileFe
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: 
            API_URL=${{ secrets.API_URL }}
